import './js/mobile_menu';
import './js/marquee';
import './js/scroll_up';
import './js/feedback';
// import './js/aos';
// import './js/aos-set';
import './js/modal';
// import './js/loader';
// import './js/scroll-up';
import './js/feedback-list';
